/**
 * Books types
 */

export const BooksTypes = {
  // BOOKS
  BOOKS_REQUEST: '@books/BOOKS_REQUEST',
  BOOKS_SUCCESS: '@books/BOOKS_SUCCESS',
  BOOKS_FAILURE: '@books/BOOKS_FAILURE',
  // BOOK_DETAILS
  BOOK_DETAILS_REQUEST: '@books/BOOK_DETAILS_REQUEST',
  BOOK_DETAILS_SUCCESS: '@books/BOOK_DETAILS_SUCCESS',
  BOOK_DETAILS_FAILURE: '@books/BOOK_DETAILS_FAILURE',
};
